site_name: rmFakeCloud
# site_url: https://github.arnaut.me/rmfakecloud/
site_description: Self hosted reMarkable sync cloud
site_author: ddvk

repo_url: https://github.com/ddvk/rmfakecloud
edit_uri: ""

theme:
  name: material
  locale: en
  
nav:
  - Home: index.md
  - Setup:
      - Device: tablet.md
      - HTTPS: https.md
  - Integrations: integrations.md
  - Browser Extension: browser-extension.md
