name: docker

on:
  push:
    branches: test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Version
        run: echo "version=$(git describe --tags)" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ddvk/rmfakecloud:latest
          build-args: |
            VERSION=${{ env.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
