name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
        cache-dependency-path: ui/yarn.lock

    - run: yarn --cwd ui
    - run: yarn --cwd ui build
    - run: CI=true yarn --cwd ui test
    - run: make test
    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        go build -tags ci -v ./cmd/rmfakecloud

    - name: Test
      run: go test -tags ci -v ./...

